### ISSUE TITLE
Check that the exported format corresponds to ICTUSNet requirements

### ISSUE THREAD

**Issue by elsiehoffet-94** [arkhn/AVC-Forms#21]
## Problem
Compare example data before and after going through AVC-Forms, to check that the columns are in the right order, and that there is no data loss.

**Comment by elsiehoffet-94** [comment]
Things to check:  

- all columns match between import and export
- 99 values are in the right place according to ictus requirements 

Use this test data : 
- example CSV provided by the consortium
- any other test csv

**Comment by Peltier10** [comment]
To consider : 
In **AVC-forms** 
- The ICTUS-data 'id event' is missing in AVC-forms
- The AVC-forms-data 'Symptoms Onset Date' can be rename as ICTUS-data 'Symptoms Onset Date or Last time seen asymptomatic' 

About **Import**
- Yesterday imports work **only** with data in **separate columns** and **with column's name.** 
- If the csv file has more than 100 patients, AVC-Forms only diplays the first 100 patients. And if you delete all patients, the first 100 patients are deleted. By refreshing the page, the next 100 patients appear, they have not been deleted.

About **Export** 
- For all DateTime in Export Nominatif, they have +1hour, is it normal ? 
(Ex : Insert CSV.hospitalArrivalDate = 2020-12-02T**13**:00:00.000Z => Export nominatif.hospitalArrivalDate = 20201203T**14**00) 
- For **boolean** : true become 0 WHEREAS it should be : (**true**;false) = (**1**;0)
- The **order** of column is different from the ICTUS-data order (see image below). Follow Ictus-data order line 
![Order Export AVC-forms Data](https://user-images.githubusercontent.com/34452954/113050530-3b923100-91a5-11eb-9cbd-7d0a669a14f0.png)

**Comment by elsiehoffet-94** [comment]
TODO :
- [ ] rename IPP -> idEvent in the column names + forms
- [ ] remove firstName & lastName in database + forms
- [ ] In the form & column label: 'Symptoms Onset Date' -> 'Symptoms Onset Date (or Last time seen asymptomatic)'
- [ ] Add line number in front, handle pagination in the back & front 
- [ ] Check time zone during import
